default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: <%= ENV.fetch('DB_HOST') { 'localhost' } %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: smartflix_development

test:
  <<: *default
  database: smartflix_test

production:
  <<: *default
  database: smartflix_production
